/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestcopyRouteImport } from './routes/testcopy'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ChatRoomsIndexRouteImport } from './routes/chatRooms/index'
import { Route as GroupsNodeIdRouteImport } from './routes/groups/$nodeId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as ChatRoomsNodeIdRouteImport } from './routes/chatRooms/$nodeId'

const TestcopyRoute = TestcopyRouteImport.update({
  id: '/testcopy',
  path: '/testcopy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomsIndexRoute = ChatRoomsIndexRouteImport.update({
  id: '/chatRooms/',
  path: '/chatRooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNodeIdRoute = GroupsNodeIdRouteImport.update({
  id: '/groups/$nodeId',
  path: '/groups/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomsNodeIdRoute = ChatRoomsNodeIdRouteImport.update({
  id: '/chatRooms/$nodeId',
  path: '/chatRooms/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/testcopy': typeof TestcopyRoute
  '/chatRooms/$nodeId': typeof ChatRoomsNodeIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/$nodeId': typeof GroupsNodeIdRoute
  '/chatRooms': typeof ChatRoomsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/testcopy': typeof TestcopyRoute
  '/chatRooms/$nodeId': typeof ChatRoomsNodeIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/$nodeId': typeof GroupsNodeIdRoute
  '/chatRooms': typeof ChatRoomsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/testcopy': typeof TestcopyRoute
  '/chatRooms/$nodeId': typeof ChatRoomsNodeIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/$nodeId': typeof GroupsNodeIdRoute
  '/chatRooms/': typeof ChatRoomsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/testcopy'
    | '/chatRooms/$nodeId'
    | '/groups/$groupId'
    | '/groups/$nodeId'
    | '/chatRooms'
    | '/groups'
    | '/login'
    | '/settings'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/testcopy'
    | '/chatRooms/$nodeId'
    | '/groups/$groupId'
    | '/groups/$nodeId'
    | '/chatRooms'
    | '/groups'
    | '/login'
    | '/settings'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/testcopy'
    | '/chatRooms/$nodeId'
    | '/groups/$groupId'
    | '/groups/$nodeId'
    | '/chatRooms/'
    | '/groups/'
    | '/login/'
    | '/settings/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  TestcopyRoute: typeof TestcopyRoute
  ChatRoomsNodeIdRoute: typeof ChatRoomsNodeIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsNodeIdRoute: typeof GroupsNodeIdRoute
  ChatRoomsIndexRoute: typeof ChatRoomsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testcopy': {
      id: '/testcopy'
      path: '/testcopy'
      fullPath: '/testcopy'
      preLoaderRoute: typeof TestcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatRooms/': {
      id: '/chatRooms/'
      path: '/chatRooms'
      fullPath: '/chatRooms'
      preLoaderRoute: typeof ChatRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$nodeId': {
      id: '/groups/$nodeId'
      path: '/groups/$nodeId'
      fullPath: '/groups/$nodeId'
      preLoaderRoute: typeof GroupsNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatRooms/$nodeId': {
      id: '/chatRooms/$nodeId'
      path: '/chatRooms/$nodeId'
      fullPath: '/chatRooms/$nodeId'
      preLoaderRoute: typeof ChatRoomsNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  TestcopyRoute: TestcopyRoute,
  ChatRoomsNodeIdRoute: ChatRoomsNodeIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsNodeIdRoute: GroupsNodeIdRoute,
  ChatRoomsIndexRoute: ChatRoomsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
